export const DOCUMENT_DATA = {
    id: 618,
    name: "Personal Injury/ Insurance Payment Demand Letter",
    description: "",
    responses: [
      {
        id: "response1",
        definition: [
          {
            name: "Parties ",
            subsections: [
              {
                name: "Sender",
                question: [
                  {
                    id: "38f1788b-e03b-4449-8375-4975bd1b428c",
                    affectedQuestion: [],
                    FAQQuestion: "Who is the sender?",
                    FAQAnswer: "The sender is the party that demands compensation due to injury.",
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "sender_name",
                    selectionValue: "name",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Who is the sender?",
                    description: "",
                    placeholder: "Enter full name",
                  },
                  {
                    id: "626016ec-f393-4d63-8062-8550def9abbf",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "sender_add",
                    selectionValue: "address",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Address",
                    description: "",
                    placeholder: "Enter street address",
                  },
                  {
                    id: "42dbcbb5-cefc-46c3-ad15-318bfb9faeea",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "sender_city",
                    selectionValue: "city",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "City",
                    description: "",
                    placeholder: "Enter city",
                  },
                  {
                    id: "44018f3c-7d98-4e0f-b1bf-77e40073a2e5",
                    affectedQuestion: [],
                    documentId: [],
                    list: [
                      {
                        name: "Alabama",
                      },
                      {
                        name: "Alaska",
                      },
                      {
                        name: "Arizona",
                      },
                      {
                        name: "Arkansas",
                      },
                      {
                        name: "California",
                      },
                      {
                        name: "Colorado",
                      },
                      {
                        name: "Connecticut",
                      },
                      {
                        name: "Delaware",
                      },
                      {
                        name: "District of Columbia",
                      },
                      {
                        name: "Florida",
                      },
                      {
                        name: "Georgia",
                      },
                      {
                        name: "Hawaii",
                      },
                      {
                        name: "Idaho",
                      },
                      {
                        name: "Illinois",
                      },
                      {
                        name: "Indiana",
                      },
                      {
                        name: "Iowa",
                      },
                      {
                        name: "Kansas",
                      },
                      {
                        name: "Kentucky",
                      },
                      {
                        name: "Louisiana",
                      },
                      {
                        name: "Maine",
                      },
                      {
                        name: "Maryland",
                      },
                      {
                        name: "Massachusetts",
                      },
                      {
                        name: "Michigan",
                      },
                      {
                        name: "Minnesota",
                      },
                      {
                        name: "Mississippi",
                      },
                      {
                        name: "Missouri",
                      },
                      {
                        name: "Montana",
                      },
                      {
                        name: "Nebraska",
                      },
                      {
                        name: "Nevada",
                      },
                      {
                        name: "New Hampshire",
                      },
                      {
                        name: "New Jersey",
                      },
                      {
                        name: "New Mexico",
                      },
                      {
                        name: "New York",
                      },
                      {
                        name: "North Carolina",
                      },
                      {
                        name: "North Dakota",
                      },
                      {
                        name: "Ohio",
                      },
                      {
                        name: "Oklahoma",
                      },
                      {
                        name: "Oregon",
                      },
                      {
                        name: "Pennsylvania",
                      },
                      {
                        name: "Rhode Island",
                      },
                      {
                        name: "South Carolina",
                      },
                      {
                        name: "South Dakota",
                      },
                      {
                        name: "Tennessee",
                      },
                      {
                        name: "Texas",
                      },
                      {
                        name: "Utah",
                      },
                      {
                        name: "Vermont",
                      },
                      {
                        name: "Virginia",
                      },
                      {
                        name: "Washington",
                      },
                      {
                        name: "West Virginia",
                      },
                      {
                        name: "Wisconsin",
                      },
                      {
                        name: "Wyoming",
                      },
                    ],
                    listDescription: [
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                    ],
                    listSubType: [],
                    uniqueKeyName: "sender_state",
                    selectionValue: "no",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "dropdownList",
                    questionToAsk: "State",
                    description: "",
                    placeholder: "",
                  },
                  {
                    id: "f47b59a2-41bb-429b-947f-89b2d3c4b729",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "sender_zip",
                    selectionValue: "zip",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Zip Code",
                    description: "",
                    placeholder: "Enter zip code",
                  },
                ],
                FAQQuestion: "What is an Injury/ Insurance Payment Demand Letter?",
                FAQAnswer:
                  "<div>An injury/ insurance payment demand letter is a formal letter used to demand compensation in the event of an accident.<br><br>It is usually addressed to an insurance company or an individual who caused damages or injuries during the accident.<br><br></div>",
              },
              {
                name: "Receiver",
                question: [
                  {
                    id: "12bc2d97-498f-4e0b-9410-79ed35a1677c",
                    affectedQuestion: [
                      {
                        id: "9f87b6a9-ba22-4bd8-aef1-798a9e11ae5c",
                        value: ["An insurance company"],
                        showOnlyIfThisMatchSelected: ["or"],
                      },
                      {
                        id: "39ffe470-00d4-4c49-9b5d-456bc8d448ec",
                        value: ["An individual"],
                        showOnlyIfThisMatchSelected: ["or"],
                      },
                    ],
                    FAQQuestion: "Who is the receiver?",
                    FAQAnswer:
                      "The receiver is the party that is demanded to compensate. It is either an insurance company or the individual that caused damages or injuries during the accident. ",
                    documentId: [],
                    list: [
                      {
                        name: "An insurance company",
                      },
                      {
                        name: "An individual",
                      },
                    ],
                    listDescription: ["", ""],
                    listSubType: [],
                    uniqueKeyName: "receiver_type",
                    selectionValue: "normal",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "radioButton",
                    questionToAsk: "Who is the receiver?",
                    description: "",
                    placeholder: "",
                  },
                  {
                    id: "9f87b6a9-ba22-4bd8-aef1-798a9e11ae5c",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "receiver_company_name",
                    selectionValue: "name",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "What is the name of the insurance company?",
                    description: "",
                    placeholder: "Enter full company name",
                  },
                  {
                    id: "39ffe470-00d4-4c49-9b5d-456bc8d448ec",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "receiver_individual_name",
                    selectionValue: "name",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "What is the name of the individual?",
                    description: "",
                    placeholder: "Enter full name",
                  },
                  {
                    id: "bfe37940-2e26-49ce-8e3a-d081069d02d2",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "receiver_add",
                    selectionValue: "address",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Address",
                    description: "",
                    placeholder: "Enter street address",
                  },
                  {
                    id: "eff0be81-49c4-4040-af44-d28a781dbea0",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "receiver_city",
                    selectionValue: "city",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "City",
                    description: "",
                    placeholder: "Enter city",
                  },
                  {
                    id: "bdb59df6-5d2f-4c81-b5a4-c42c856ce311",
                    affectedQuestion: [],
                    documentId: [],
                    list: [
                      {
                        name: "Alabama",
                      },
                      {
                        name: "Alaska",
                      },
                      {
                        name: "Arizona",
                      },
                      {
                        name: "Arkansas",
                      },
                      {
                        name: "California",
                      },
                      {
                        name: "Colorado",
                      },
                      {
                        name: "Connecticut",
                      },
                      {
                        name: "Delaware",
                      },
                      {
                        name: "District of Columbia",
                      },
                      {
                        name: "Florida",
                      },
                      {
                        name: "Georgia",
                      },
                      {
                        name: "Hawaii",
                      },
                      {
                        name: "Idaho",
                      },
                      {
                        name: "Illinois",
                      },
                      {
                        name: "Indiana",
                      },
                      {
                        name: "Iowa",
                      },
                      {
                        name: "Kansas",
                      },
                      {
                        name: "Kentucky",
                      },
                      {
                        name: "Louisiana",
                      },
                      {
                        name: "Maine",
                      },
                      {
                        name: "Maryland",
                      },
                      {
                        name: "Massachusetts",
                      },
                      {
                        name: "Michigan",
                      },
                      {
                        name: "Minnesota",
                      },
                      {
                        name: "Mississippi",
                      },
                      {
                        name: "Missouri",
                      },
                      {
                        name: "Montana",
                      },
                      {
                        name: "Nebraska",
                      },
                      {
                        name: "Nevada",
                      },
                      {
                        name: "New Hampshire",
                      },
                      {
                        name: "New Jersey",
                      },
                      {
                        name: "New Mexico",
                      },
                      {
                        name: "New York",
                      },
                      {
                        name: "North Carolina",
                      },
                      {
                        name: "North Dakota",
                      },
                      {
                        name: "Ohio",
                      },
                      {
                        name: "Oklahoma",
                      },
                      {
                        name: "Oregon",
                      },
                      {
                        name: "Pennsylvania",
                      },
                      {
                        name: "Rhode Island",
                      },
                      {
                        name: "South Carolina",
                      },
                      {
                        name: "South Dakota",
                      },
                      {
                        name: "Tennessee",
                      },
                      {
                        name: "Texas",
                      },
                      {
                        name: "Utah",
                      },
                      {
                        name: "Vermont",
                      },
                      {
                        name: "Virginia",
                      },
                      {
                        name: "Washington",
                      },
                      {
                        name: "West Virginia",
                      },
                      {
                        name: "Wisconsin",
                      },
                      {
                        name: "Wyoming",
                      },
                    ],
                    listDescription: [
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                      "",
                    ],
                    listSubType: [],
                    uniqueKeyName: "receiver_state",
                    selectionValue: "no",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "dropdownList",
                    questionToAsk: "State",
                    description: "",
                    placeholder: "",
                  },
                  {
                    id: "d4ad5dd4-10ee-4c48-b9f6-d8e31fe4af5b",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "receiver_zip",
                    selectionValue: "zip",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Zip Code",
                    description: "",
                    placeholder: "Enter zip code",
                  },
                ],
              },
            ],
          },
          {
            name: "Payment",
            subsections: [
              {
                name: "Payment",
                question: [
                  {
                    id: "ba638989-c0ba-4b01-9ee0-8e52d437fd95",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "pay_amt",
                    selectionValue: "currency",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "What is the total demanded amount of compensation?",
                    description: "",
                    placeholder: "",
                  },
                  {
                    id: "8f203bc2-ca24-4063-8132-420b6c93772b",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "pay_reason",
                    selectionValue: "textbox",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Describe the accident or the event that leads to injuries/ damages:",
                    description:
                      "This should include the date of the accident, where it happened, and a summary of the event.",
                    placeholder:
                      "e.g. On March 2nd on Second Street in Jersey City, New Jersey, the rear-end of my vehicle was hit by your/ a van when stopping at an intersection stop sign.",
                  },
                  {
                    id: "512ab2d0-3fae-428e-ae29-2d484d5ea9d8",
                    affectedQuestion: [
                      {
                        id: "cd4ff6b4-8733-4278-8d6f-0b249689494b",
                        value: ["Yes"],
                        showOnlyIfThisMatchSelected: ["or"],
                      },
                    ],
                    FAQQuestion: "What is a compensation breakdown?",
                    FAQAnswer:
                      "<div>A compensation breakdown is a summary of the damages and injuries the accident caused and how they should be compensated.</div>",
                    documentId: [],
                    list: [
                      {
                        name: "Yes",
                      },
                      {
                        name: "No",
                      },
                    ],
                    listDescription: [null, null],
                    listSubType: [],
                    uniqueKeyName: "pay_breakdown_option",
                    selectionValue: "normal",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "radioButton",
                    questionToAsk: "Do you want to provide a breakdown of the compensation amount?",
                    description: "",
                    placeholder: "",
                  },
                  {
                    id: "cd4ff6b4-8733-4278-8d6f-0b249689494b",
                    affectedQuestion: [
                      {
                        id: "e7a79d87-9612-4a69-99dc-ccc8e10279df",
                        value: ["Injuries/ treatment"],
                        showOnlyIfThisMatchSelected: ["or"],
                      },
                      {
                        id: "e03f7ad9-7bc2-410e-885c-2d3e6ca0de3f",
                        value: ["Injuries/ treatment"],
                        showOnlyIfThisMatchSelected: ["or"],
                      },
                      {
                        id: "681214cf-a9f2-41e6-ae5b-07fca31db5cf",
                        value: ["Out-of-pocket expenses"],
                        showOnlyIfThisMatchSelected: ["or"],
                      },
                      {
                        id: "47c795d0-70c8-4c3b-bd07-640ccfb7d9fa",
                        value: ["Out-of-pocket expenses"],
                        showOnlyIfThisMatchSelected: ["or"],
                      },
                      {
                        id: "a9c88f8e-a027-43d2-8aa1-b9de9d69c12f",
                        value: ["Lost wages/ earnings"],
                        showOnlyIfThisMatchSelected: ["or"],
                      },
                      {
                        id: "20f719c8-cf4f-41b2-84f1-882fecc85b0b",
                        value: ["Lost wages/ earnings"],
                        showOnlyIfThisMatchSelected: ["or"],
                      },
                      {
                        id: "a1c89105-1495-4153-82d4-d555d86e5822",
                        value: ["Pain and suffering"],
                        showOnlyIfThisMatchSelected: ["or"],
                      },
                      {
                        id: "36ccd1ce-4550-408b-94f1-9e5bb765c26f",
                        value: ["Pain and suffering"],
                        showOnlyIfThisMatchSelected: ["or"],
                      },
                    ],
                    FAQQuestion: "What are the common types of compensation in an injury/ insurance claim?",
                    FAQAnswer:
                      "<div>Injuries/ treatment: This covers medical expenses such as hospital stays, treatment, and rehabilitation bills.<br><br>Out-of-pocket expenses: This covers costs associated with property damage, including repair and replacement.<br><br>Lost wages/ earnings: This covers loss of wages and reductions in earning potential due to injury.<br><br>Pain and suffering: This covers long-term physical or mental pain due to injury or treatment.<br><br></div>",
                    documentId: [],
                    list: [
                      {
                        name: "Injuries/ treatment",
                      },
                      {
                        name: "Out-of-pocket expenses",
                      },
                      {
                        name: "Lost wages/ earnings",
                      },
                      {
                        name: "Pain and suffering",
                      },
                    ],
                    listDescription: ["", "", "", ""],
                    listSubType: [],
                    uniqueKeyName: "pay_breakdown",
                    selectionValue: "normal",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "checkboxes",
                    questionToAsk: "What type(s) of compensation should be included in the breakdown?",
                    description: "",
                    placeholder: "",
                  },
                ],
              },
              {
                name: "Injuries/ Treatment",
                question: [
                  {
                    id: "e7a79d87-9612-4a69-99dc-ccc8e10279df",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "injury_amount",
                    selectionValue: "currency",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Amount:",
                    description: "",
                    placeholder: "",
                  },
                  {
                    id: "e03f7ad9-7bc2-410e-885c-2d3e6ca0de3f",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "injury_description",
                    selectionValue: "textbox",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Describe the injuries sustained in the accident and what treatment was received:",
                    description: "",
                    placeholder: "e.g. broken arm requiring surgery to be performed",
                  },
                ],
              },
              {
                name: "Lost Wages/ Earnings",
                question: [
                  {
                    id: "a9c88f8e-a027-43d2-8aa1-b9de9d69c12f",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "wage_amount",
                    selectionValue: "currency",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Amount:",
                    description: "",
                    placeholder: "",
                  },
                  {
                    id: "20f719c8-cf4f-41b2-84f1-882fecc85b0b",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "wage_description",
                    selectionValue: "textbox",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Describe how wages/ earnings were lost due to the accident:",
                    description: "",
                    placeholder: "e.g. incapacity to work for two months due to the injury sustained from the accident",
                  },
                ],
              },
              {
                name: "Out-of-Pocket Expanses",
                question: [
                  {
                    id: "681214cf-a9f2-41e6-ae5b-07fca31db5cf",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "pocket_amount",
                    selectionValue: "currency",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Amount:",
                    description: "",
                    placeholder: "",
                  },
                  {
                    id: "47c795d0-70c8-4c3b-bd07-640ccfb7d9fa",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "pocket_description",
                    selectionValue: "textbox",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Describe out-of-pocket expenses incurred from the accident:",
                    description: "",
                    placeholder: "e.g. repairing broken windshield",
                  },
                ],
              },
              {
                name: "Pain and Suffering",
                question: [
                  {
                    id: "a1c89105-1495-4153-82d4-d555d86e5822",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "pain_amount",
                    selectionValue: "currency",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Amount:",
                    description: "",
                    placeholder: "",
                  },
                  {
                    id: "36ccd1ce-4550-408b-94f1-9e5bb765c26f",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "pain_description",
                    selectionValue: "textbox",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "Describe suffering as the result of the accident:",
                    description: "",
                    placeholder: "e.g. difficulty in walking resulting in the need to use crutches",
                  },
                ],
              },
              {
                name: "Due date",
                question: [
                  {
                    id: "ac694074-b29c-434c-b495-4a2f8387f2fe",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "pay_due_date",
                    selectionValue: "date",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "When is the compensation due?",
                    description: "",
                    placeholder: "",
                  },
                ],
              },
            ],
          },
          {
            name: "Final Details",
            subsections: [
              {
                name: "Date",
                question: [
                  {
                    id: "835bd7a0-a166-44fd-a112-11245cb34edb",
                    affectedQuestion: [],
                    documentId: [],
                    list: [],
                    listDescription: [],
                    listSubType: [],
                    uniqueKeyName: "letter_date",
                    selectionValue: "date",
                    isRequired: false,
                    isAutoFillAddress: false,
                    defaultValue: "",
                    formattedIDType: "",
                    type: "textField",
                    questionToAsk: "What is the date of this letter?",
                    description: "",
                    placeholder: "",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    instruction: {},
    font: "Arial",
    markup_margin: {
      top: 2.54,
      bottom: 2.54,
      left: 2.54,
      right: 2.54,
    },
    instruction_margin: {
      top: 2.54,
      right: 1.06,
      bottom: 2.54,
      left: 1.06,
    },
    header_footer: {
      footer:
        '<div><span style="font-size: 8px;"><strong>Personal Injury/ Insurance Payment Demand Letter</strong> (Rev. 134AFDD)</span></div>',
    },
    target_nation: "US",
    pdf_only: false,
  }
  
  